version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/auth-api
      - JWT_SECRET=secret
      - JWT_EXPIRE=1h
      - REFRESH_TOKEN_SECRET=refresh_secret
      - REFRESH_TOKEN_EXPIRE=7d
      - STRIPE_SECRET_KEY=sk_test_123456
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
