name: Deploy to VPS

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_HOST_USER }}
          password: ${{ secrets.SSH_HOST_PASSWORD }}
          script: |
            cd ~/PxlHut
            git pull
            yarn install
            pm2 restart PxlHut
